# Generated by Django 3.2.4 on 2021-06-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Others', 'o'), ('Female', 'f'), ('Male', 'm')], max_length=8)),
                ('locality', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pin_code', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Rangpur', 'rangpur'), ('Dhaka', 'dhaka'), ('Khulna', 'khunla'), ('Rajshahi', 'rajshahi'), ('Chitfagram', 'chitfagram'), ('Borishal', 'borishal')], max_length=20)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(blank=True, upload_to='profileimg/')),
                ('my_file', models.FileField(blank=True, upload_to='myfile/')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
