# Generated by Django 3.2.4 on 2021-06-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210623_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_info',
            name='gender',
            field=models.CharField(choices=[('o', 'Others'), ('f', 'Female'), ('m', 'Male')], max_length=8),
        ),
        migrations.AlterField(
            model_name='resume_info',
            name='state',
            field=models.CharField(choices=[('chitfagram', 'Chitfagram'), ('rangpur', 'Rangpur'), ('dhaka', 'Dhaka'), ('borishal', 'Borishal'), ('rajshahi', 'Rajshahi'), ('khunla', 'Khulna')], max_length=20),
        ),
    ]
