# Generated by Django 3.2.4 on 2021-06-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20210623_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_info',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profileimg/'),
        ),
        migrations.AlterField(
            model_name='resume_info',
            name='state',
            field=models.CharField(choices=[('chitfagram', 'Chitfagram'), ('rajshahi', 'Rajshahi'), ('borishal', 'Borishal'), ('khunla', 'Khulna'), ('rangpur', 'Rangpur'), ('dhaka', 'Dhaka')], max_length=20),
        ),
    ]
